"""added roles to users

Revision ID: 4792c8be3407
Revises: 48f35b56fc5b
Create Date: 2022-09-12 12:30:00.978774

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

revision = '4792c8be3407'
down_revision = '48f35b56fc5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    role = postgresql.ENUM('admin', 'client', 'staff', 'contractor', name='role')
    role.create(op.get_bind())
    op.add_column('user',
                  sa.Column('role', sa.Enum('admin', 'client', 'staff', 'contractor', name='role'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
    role = postgresql.ENUM('admin', 'client', 'staff', 'contractor', name='role')
    role.drop(op.get_bind())
