"""delete role types

Revision ID: 4fa17b03512a
Revises: 4792c8be3407
Create Date: 2022-09-12 18:06:40.968326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa17b03512a'
down_revision = '4792c8be3407'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
