apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
  annotations:
    fluxcd.io/tag.user-service: semver:~1.0
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: izzattilla706/user_service:1.0.2
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB

            - name: POSTGRES_SERVER
              valueFrom:
                configMapKeyRef:
                  name: postgres-secret
                  key: DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    app: user-service
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000